name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-7

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.9
    - name: Create new project
      run: dotnet new console
    - name: Install Guilded.NET
      run: dotnet add package Guilded.NET --version 0.0.1
